export type Locale = "en" | "es-419" | "fr" | "zh-CN" | "nl" | "de" | "pt-BR" | "ja" | "ko" | "ar" | "pl" | "it" | "tr" | "ru";

export const LOCALES: { id: Locale; label: string; native: string }[] = [
  { id: "en", label: "English", native: "English" },
  { id: "es-419", label: "Simplified Spanish", native: "Español (Latinoamérica)" },
  { id: "fr", label: "French", native: "Français" },
  { id: "zh-CN", label: "Simplified Chinese", native: "简体中文" },
  { id: "nl", label: "Dutch", native: "Nederlands" },
  { id: "de", label: "German", native: "Deutsch" },
  { id: "pt-BR", label: "Portuguese (Brazil)", native: "Português (Brasil)" },
  { id: "ja", label: "Japanese", native: "日本語" },
  { id: "ko", label: "Korean", native: "한국어" },
  { id: "ar", label: "Arabic", native: "العربية" },
  { id: "pl", label: "Polish", native: "Polski" },
  { id: "it", label: "Italian", native: "Italiano" },
  { id: "tr", label: "Turkish", native: "Türkçe" },
  { id: "ru", label: "Russian", native: "Русский" },
];

const strings: Record<Locale, Record<string, string>> = {
  en: {},
  "es-419": {
    Profile: "Perfil", Identity: "Identidad", "Display name": "Nombre para mostrar", Pronouns: "Pronombres",
    "Level": "Nivel", "Field of study": "Área de estudio", "About you": "Sobre ti", Memory: "Memoria",
    "Save profile": "Guardar perfil", Remember: "Recordar", "No memories yet. Add a fact above and the AI will keep it in mind.": "Aún no hay recuerdos. Añade un dato y la IA lo tendrá en cuenta.",
    "Google Calendar": "Calendario de Google", "Sync now": "Sincronizar ahora", Calendar: "Calendario", References: "Referencias",
    Assignments: "Tareas", "Copy all": "Copiar todo", Import: "Importar", Export: "Exportar", New: "Nuevo",
    "Study music": "Música de estudio", Stations: "Estaciones", "Your stations": "Tus estaciones", Favourites: "Favoritos",
  },
  fr: { Profile: "Profil", Identity: "Identité", "Display name": "Nom affiché", Pronouns: "Pronoms", Level: "Niveau", "Field of study": "Domaine d’étude", "About you": "À propos de vous", Memory: "Mémoire", "Save profile": "Enregistrer le profil", Remember: "Mémoriser", "Google Calendar": "Google Agenda", "Sync now": "Synchroniser", Calendar: "Agenda", References: "Références", Assignments: "Devoirs", "Copy all": "Tout copier", Import: "Importer", Export: "Exporter", New: "Nouveau", "Study music": "Musique d’étude", Stations: "Stations", "Your stations": "Vos stations", Favourites: "Favoris" },
  "zh-CN": { Profile: "个人资料", Identity: "身份", "Display name": "显示名称", Pronouns: "代词", Level: "学习阶段", "Field of study": "学习领域", "About you": "关于你", Memory: "记忆", "Save profile": "保存资料", Remember: "记住", "Google Calendar": "Google 日历", "Sync now": "立即同步", Calendar: "日历", References: "参考文献", Assignments: "作业", "Copy all": "全部复制", Import: "导入", Export: "导出", New: "新建", "Study music": "学习音乐", Stations: "电台", "Your stations": "你的电台", Favourites: "收藏" },
  nl: { Profile: "Profiel", Identity: "Identiteit", "Display name": "Weergavenaam", Pronouns: "Voornaamwoorden", Level: "Niveau", "Field of study": "Studiegebied", "About you": "Over jou", Memory: "Geheugen", "Save profile": "Profiel opslaan", Remember: "Onthouden", "Google Calendar": "Google Agenda", "Sync now": "Nu synchroniseren", Calendar: "Agenda", References: "Referenties", Assignments: "Opdrachten", "Copy all": "Alles kopiëren", Import: "Importeren", Export: "Exporteren", New: "Nieuw", "Study music": "Studiemuziek", Stations: "Stations", "Your stations": "Jouw stations", Favourites: "Favorieten" },
  de: { Profile: "Profil", Identity: "Identität", "Display name": "Anzeigename", Pronouns: "Pronomen", Level: "Niveau", "Field of study": "Studienfach", "About you": "Über dich", Memory: "Erinnerungen", "Save profile": "Profil speichern", Remember: "Merken", "Google Calendar": "Google Kalender", "Sync now": "Jetzt synchronisieren", Calendar: "Kalender", References: "Quellen", Assignments: "Aufgaben", "Copy all": "Alles kopieren", Import: "Importieren", Export: "Exportieren", New: "Neu", "Study music": "Lernmusik", Stations: "Sender", "Your stations": "Deine Sender", Favourites: "Favoriten" },
  "pt-BR": { Profile: "Perfil", Identity: "Identidade", "Display name": "Nome de exibição", Pronouns: "Pronomes", Level: "Nível", "Field of study": "Área de estudo", "About you": "Sobre você", Memory: "Memória", "Save profile": "Salvar perfil", Remember: "Lembrar", "Google Calendar": "Google Agenda", "Sync now": "Sincronizar agora", Calendar: "Calendário", References: "Referências", Assignments: "Tarefas", "Copy all": "Copiar tudo", Import: "Importar", Export: "Exportar", New: "Novo", "Study music": "Música de estudo", Stations: "Estações", "Your stations": "Suas estações", Favourites: "Favoritos" },
  ja: { Profile: "プロフィール", Identity: "基本情報", "Display name": "表示名", Pronouns: "代名詞", Level: "レベル", "Field of study": "専攻", "About you": "あなたについて", Memory: "メモリー", "Save profile": "プロフィールを保存", Remember: "記憶する", "Google Calendar": "Google カレンダー", "Sync now": "今すぐ同期", Calendar: "カレンダー", References: "参考文献", Assignments: "課題", "Copy all": "すべてコピー", Import: "インポート", Export: "エクスポート", New: "新規", "Study music": "学習用音楽", Stations: "ステーション", "Your stations": "自分のステーション", Favourites: "お気に入り" },
  ko: { Profile: "프로필", Identity: "신원", "Display name": "표시 이름", Pronouns: "대명사", Level: "수준", "Field of study": "전공", "About you": "나에 대해", Memory: "메모리", "Save profile": "프로필 저장", Remember: "기억하기", "Google Calendar": "Google 캘린더", "Sync now": "지금 동기화", Calendar: "캘린더", References: "참고문헌", Assignments: "과제", "Copy all": "모두 복사", Import: "가져오기", Export: "내보내기", New: "새로 만들기", "Study music": "학습 음악", Stations: "스테이션", "Your stations": "내 스테이션", Favourites: "즐겨찾기" },
  ar: { Profile: "الملف الشخصي", Identity: "الهوية", "Display name": "اسم العرض", Pronouns: "الضمائر", Level: "المستوى", "Field of study": "مجال الدراسة", "About you": "عن نفسك", Memory: "الذاكرة", "Save profile": "حفظ الملف الشخصي", Remember: "تذكّر", "Google Calendar": "تقويم Google", "Sync now": "مزامنة الآن", Calendar: "التقويم", References: "المراجع", Assignments: "المهام", "Copy all": "نسخ الكل", Import: "استيراد", Export: "تصدير", New: "جديد", "Study music": "موسيقى الدراسة", Stations: "المحطات", "Your stations": "محطاتك", Favourites: "المفضلة" },
  pl: { Profile: "Profil", Identity: "Tożsamość", "Display name": "Nazwa wyświetlana", Pronouns: "Zaimki", Level: "Poziom", "Field of study": "Kierunek studiów", "About you": "O Tobie", Memory: "Pamięć", "Save profile": "Zapisz profil", Remember: "Zapamiętaj", "Google Calendar": "Kalendarz Google", "Sync now": "Synchronizuj teraz", Calendar: "Kalendarz", References: "Bibliografia", Assignments: "Zadania", "Copy all": "Kopiuj wszystko", Import: "Importuj", Export: "Eksportuj", New: "Nowy", "Study music": "Muzyka do nauki", Stations: "Stacje", "Your stations": "Twoje stacje", Favourites: "Ulubione" },
  it: { Profile: "Profilo", Identity: "Identità", "Display name": "Nome visualizzato", Pronouns: "Pronomi", Level: "Livello", "Field of study": "Campo di studio", "About you": "Informazioni su di te", Memory: "Memoria", "Save profile": "Salva profilo", Remember: "Ricorda", "Google Calendar": "Google Calendar", "Sync now": "Sincronizza ora", Calendar: "Calendario", References: "Riferimenti", Assignments: "Attività", "Copy all": "Copia tutto", Import: "Importa", Export: "Esporta", New: "Nuovo", "Study music": "Musica per lo studio", Stations: "Stazioni", "Your stations": "Le tue stazioni", Favourites: "Preferiti" },
  tr: { Profile: "Profil", Identity: "Kimlik", "Display name": "Görünen ad", Pronouns: "Zamirler", Level: "Seviye", "Field of study": "Çalışma alanı", "About you": "Hakkında", Memory: "Hafıza", "Save profile": "Profili kaydet", Remember: "Hatırla", "Google Calendar": "Google Takvim", "Sync now": "Şimdi senkronize et", Calendar: "Takvim", References: "Kaynaklar", Assignments: "Ödevler", "Copy all": "Tümünü kopyala", Import: "İçe aktar", Export: "Dışa aktar", New: "Yeni", "Study music": "Çalışma müziği", Stations: "İstasyonlar", "Your stations": "İstasyonların", Favourites: "Favoriler" },
  ru: { Profile: "Профиль", Identity: "Личные данные", "Display name": "Отображаемое имя", Pronouns: "Местоимения", Level: "Уровень", "Field of study": "Область обучения", "About you": "О вас", Memory: "Память", "Save profile": "Сохранить профиль", Remember: "Запомнить", "Google Calendar": "Google Календарь", "Sync now": "Синхронизировать", Calendar: "Календарь", References: "Источники", Assignments: "Задания", "Copy all": "Копировать всё", Import: "Импорт", Export: "Экспорт", New: "Новое", "Study music": "Музыка для учёбы", Stations: "Станции", "Your stations": "Ваши станции", Favourites: "Избранное" },
};

const profileCopy: Record<Locale, Record<string, string>> = {
  en: {}, "es-419": {}, fr: {}, "zh-CN": {}, nl: {}, de: {}, "pt-BR": {}, ja: {}, ko: {}, ar: {},
  pl: { "Who the AI thinks you are": "Jak AI Cię postrzega", "Shared with every chat and generation so answers fit your level and style. Stays on this machine.": "Udostępniane każdemu czatowi i generowaniu, aby odpowiedzi pasowały do Twojego poziomu i stylu. Pozostaje na tym urządzeniu.", "Undergraduate": "Studia licencjackie", Postgraduate: "Studia magisterskie", "PhD / research": "Doktorat / badania", "Self-study": "Samodzielna nauka", "Context the AI uses to personalize explanations.": "Kontekst używany przez AI do personalizacji wyjaśnień.", "In your words": "Twoimi słowami", "Response style": "Styl odpowiedzi", "How much detail by default.": "Domyślny poziom szczegółowości.", "Explain with": "Wyjaśniaj za pomocą", "Pick what helps you learn fastest.": "Wybierz to, co pomaga Ci uczyć się najszybciej.", "Long-term facts the AI is given in every chat — like remembering your exam date, the textbook you use, or how you like answers framed.": "Długoterminowe informacje przekazywane AI w każdym czacie — na przykład data egzaminu, używany podręcznik lub preferowany sposób odpowiedzi.", "e.g. My final exam is on June 20th": "np. Mój egzamin końcowy jest 20 czerwca", "What the AI receives": "Co otrzymuje AI", Concise: "Zwięzły", Balanced: "Zrównoważony", Detailed: "Szczegółowy" },
  it: { "Who the AI thinks you are": "Come ti vede l'IA", "Shared with every chat and generation so answers fit your level and style. Stays on this machine.": "Condiviso con ogni chat e generazione per adattare le risposte al tuo livello e stile. Rimane su questo dispositivo.", "Undergraduate": "Laurea triennale", Postgraduate: "Laurea magistrale", "PhD / research": "Dottorato / ricerca", "Self-study": "Studio autonomo", "Context the AI uses to personalize explanations.": "Contesto usato dall'IA per personalizzare le spiegazioni.", "In your words": "Con le tue parole", "Response style": "Stile delle risposte", "How much detail by default.": "Livello di dettaglio predefinito.", "Explain with": "Spiega con", "Pick what helps you learn fastest.": "Scegli ciò che ti aiuta a imparare più velocemente.", "Long-term facts the AI is given in every chat — like remembering your exam date, the textbook you use, or how you like answers framed.": "Informazioni durature fornite all'IA in ogni chat, come la data dell'esame o il modo in cui preferisci le risposte.", "e.g. My final exam is on June 20th": "es. Il mio esame finale è il 20 giugno", "What the AI receives": "Cosa riceve l'IA", Concise: "Conciso", Balanced: "Bilanciato", Detailed: "Dettagliato" },
  tr: { "Who the AI thinks you are": "Yapay zekânın seni nasıl gördüğü", "Shared with every chat and generation so answers fit your level and style. Stays on this machine.": "Yanıtların seviyene ve tarzına uyması için her sohbet ve üretimle paylaşılır. Bu cihazda kalır.", "Undergraduate": "Lisans", Postgraduate: "Lisansüstü", "PhD / research": "Doktora / araştırma", "Self-study": "Kendi kendine çalışma", "Context the AI uses to personalize explanations.": "Yapay zekânın açıklamaları kişiselleştirmek için kullandığı bağlam.", "In your words": "Kendi sözlerinle", "Response style": "Yanıt stili", "How much detail by default.": "Varsayılan ayrıntı düzeyi.", "Explain with": "Şunlarla açıkla", "Pick what helps you learn fastest.": "En hızlı öğrenmene yardımcı olanları seç.", "What the AI receives": "Yapay zekânın aldığı", Concise: "Kısa", Balanced: "Dengeli", Detailed: "Ayrıntılı" },
  ru: { "Who the AI thinks you are": "Как ИИ вас воспринимает", "Shared with every chat and generation so answers fit your level and style. Stays on this machine.": "Используется в каждом чате и при каждой генерации, чтобы ответы соответствовали вашему уровню и стилю. Хранится на этом устройстве.", "Undergraduate": "Бакалавриат", Postgraduate: "Магистратура", "PhD / research": "Аспирантура / исследования", "Self-study": "Самостоятельное обучение", "Context the AI uses to personalize explanations.": "Контекст, который ИИ использует для персонализации объяснений.", "In your words": "Вашими словами", "Response style": "Стиль ответа", "How much detail by default.": "Уровень подробности по умолчанию.", "Explain with": "Объяснять с помощью", "Pick what helps you learn fastest.": "Выберите то, что помогает учиться быстрее.", "What the AI receives": "Что получает ИИ", Concise: "Кратко", Balanced: "Сбалансированно", Detailed: "Подробно" },
};

const commonCopy: Record<Locale, Record<string, string>> = {
  en: {},
  "es-419": { "Study sound": "Sonido de estudio", "Now playing": "Reproduciendo", "ad-free": "sin anuncios", "Favourites": "Favoritos", "Your stations": "Tus estaciones", Stations: "Estaciones", "Add a YouTube station": "Añadir estación de YouTube", "Play / pause": "Reproducir / pausar", "Space leader — context actions": "Líder de espacio — acciones de contexto" },
  fr: { "Study sound": "Son d’étude", "Now playing": "Lecture en cours", "ad-free": "sans publicité", Favourites: "Favoris", "Your stations": "Vos stations", Stations: "Stations", "Add a YouTube station": "Ajouter une station YouTube", "Play / pause": "Lire / pause", "Space leader — context actions": "Leader espace — actions contextuelles" },
  "zh-CN": { "Study sound": "学习声音", "Now playing": "正在播放", "ad-free": "无广告", Favourites: "收藏", "Your stations": "你的电台", Stations: "电台", "Add a YouTube station": "添加 YouTube 电台", "Play / pause": "播放 / 暂停", "Space leader — context actions": "空格领导 — 上下文操作" },
  nl: { "Study sound": "Studiegeluid", "Now playing": "Nu aan het afspelen", "ad-free": "zonder advertenties", Favourites: "Favorieten", "Your stations": "Jouw stations", Stations: "Stations", "Add a YouTube station": "YouTube-station toevoegen", "Play / pause": "Afspelen / pauzeren", "Space leader — context actions": "Spatieleider — contextacties" },
  de: { "Study sound": "Lernklang", "Now playing": "Wird abgespielt", "ad-free": "werbefrei", Favourites: "Favoriten", "Your stations": "Deine Sender", Stations: "Sender", "Add a YouTube station": "YouTube-Sender hinzufügen", "Play / pause": "Wiedergabe / Pause", "Space leader — context actions": "Leertaste — Kontextaktionen" },
  "pt-BR": { "Study sound": "Som de estudo", "Now playing": "Reproduzindo agora", "ad-free": "sem anúncios", Favourites: "Favoritos", "Your stations": "Suas estações", Stations: "Estações", "Add a YouTube station": "Adicionar estação do YouTube", "Play / pause": "Reproduzir / pausar", "Space leader — context actions": "Espaço — ações de contexto" },
  ja: { "Study sound": "学習サウンド", "Now playing": "再生中", "ad-free": "広告なし", Favourites: "お気に入り", "Your stations": "自分のステーション", Stations: "ステーション", "Add a YouTube station": "YouTubeステーションを追加", "Play / pause": "再生 / 一時停止", "Space leader — context actions": "スペースリーダー — コンテキスト操作" },
  ko: { "Study sound": "학습 사운드", "Now playing": "현재 재생", "ad-free": "광고 없음", Favourites: "즐겨찾기", "Your stations": "내 스테이션", Stations: "스테이션", "Add a YouTube station": "YouTube 스테이션 추가", "Play / pause": "재생 / 일시정지", "Space leader — context actions": "스페이스 리더 — 컨텍스트 작업" },
  ar: { "Study sound": "صوت الدراسة", "Now playing": "يعمل الآن", "ad-free": "بدون إعلانات", Favourites: "المفضلة", "Your stations": "محطاتك", Stations: "المحطات", "Add a YouTube station": "إضافة محطة YouTube", "Play / pause": "تشغيل / إيقاف مؤقت", "Space leader — context actions": "قائد المسافة — إجراءات السياق" },
  pl: { "Study sound": "Dźwięk do nauki", "Now playing": "Teraz odtwarzane", "ad-free": "bez reklam", Favourites: "Ulubione", "Your stations": "Twoje stacje", Stations: "Stacje", "Add a YouTube station": "Dodaj stację YouTube", "Play / pause": "Odtwórz / pauza", "Space leader — context actions": "Spacja — akcje kontekstowe" },
  it: { "Study sound": "Suono per lo studio", "Now playing": "In riproduzione", "ad-free": "senza pubblicità", Favourites: "Preferiti", "Your stations": "Le tue stazioni", Stations: "Stazioni", "Add a YouTube station": "Aggiungi stazione YouTube", "Play / pause": "Riproduci / pausa", "Space leader — context actions": "Spazio — azioni contestuali" },
  tr: { "Study sound": "Çalışma sesi", "Now playing": "Şimdi çalıyor", "ad-free": "reklamsız", Favourites: "Favoriler", "Your stations": "İstasyonların", Stations: "İstasyonlar", "Add a YouTube station": "YouTube istasyonu ekle", "Play / pause": "Oynat / duraklat", "Space leader — context actions": "Boşluk lideri — bağlam eylemleri" },
  ru: { "Study sound": "Звук для учёбы", "Now playing": "Сейчас играет", "ad-free": "без рекламы", Favourites: "Избранное", "Your stations": "Ваши станции", Stations: "Станции", "Add a YouTube station": "Добавить станцию YouTube", "Play / pause": "Воспроизвести / пауза", "Space leader — context actions": "Пробел — контекстные действия" },
};

// This module is regular TypeScript, not a .svelte component. Keep the shared
// locale as a plain value; using the $state rune here would be emitted as a
// runtime identifier and crash the production WebView.
export let activeLocale: Locale = "en";

export function setLocale(locale: Locale): void { activeLocale = locale; }

export function translate(locale: Locale, text: string): string {
  const nav: Record<string, Partial<Record<Locale, string>>> = {
    Dashboard: { fr: "Tableau de bord", "zh-CN": "仪表板", nl: "Dashboard", de: "Dashboard", "pt-BR": "Painel", ja: "ダッシュボード", ko: "대시보드", ar: "لوحة التحكم", pl: "Panel", it: "Dashboard", tr: "Gösterge paneli", ru: "Панель" },
    "Record lecture": { fr: "Enregistrer un cours", "zh-CN": "录制讲座", nl: "College opnemen", de: "Vorlesung aufnehmen", "pt-BR": "Gravar aula", ja: "講義を録音", ko: "강의 녹음", ar: "تسجيل المحاضرة", pl: "Nagraj wykład", it: "Registra lezione", tr: "Ders kaydet", ru: "Записать лекцию" },
    "Add source": { fr: "Ajouter une source", "zh-CN": "添加来源", nl: "Bron toevoegen", de: "Quelle hinzufügen", "pt-BR": "Adicionar fonte", ja: "ソースを追加", ko: "자료 추가", ar: "إضافة مصدر", pl: "Dodaj źródło", it: "Aggiungi fonte", tr: "Kaynak ekle", ru: "Добавить источник" },
    Notes: { fr: "Notes", "zh-CN": "笔记", nl: "Notities", de: "Notizen", "pt-BR": "Notas", ja: "ノート", ko: "노트", ar: "ملاحظات", pl: "Notatki", it: "Note", tr: "Notlar", ru: "Заметки" },
    Calendar: { fr: "Calendrier", "zh-CN": "日历", nl: "Agenda", de: "Kalender", "pt-BR": "Calendário", ja: "カレンダー", ko: "캘린더", ar: "التقويم", pl: "Kalendarz", it: "Calendario", tr: "Takvim", ru: "Календарь" },
    Insights: { fr: "Analyses", "zh-CN": "洞察", nl: "Inzichten", de: "Einblicke", "pt-BR": "Insights", ja: "インサイト", ko: "인사이트", ar: "التحليلات", pl: "Analizy", it: "Analisi", tr: "İçgörüler", ru: "Аналитика" },
    Subjects: { fr: "Matières", "zh-CN": "科目", nl: "Vakken", de: "Fächer", "pt-BR": "Disciplinas", ja: "科目", ko: "과목", ar: "المواد", pl: "Przedmioty", it: "Materie", tr: "Dersler", ru: "Предметы" },
  };
  return strings[locale][text] ?? profileCopy[locale][text] ?? commonCopy[locale][text] ?? nav[text]?.[locale] ?? text;
}

export function t(text: string): string { return translate(activeLocale, text); }
