<script lang="ts">
  import { app } from "../lib/store.svelte";
  import Icon from "../components/Icon.svelte";
  type Game = "2048" | "quiz" | "mines";
  let game = $state<Game>("2048");
  let cells = $state<string[]>(Array(9).fill(""));
  let turn = $state<"X" | "O">("X");
  let board = $state<number[]>(Array(16).fill(0));
  let score = $state(0);
  let mines = $state<number[]>([]), revealed = $state<boolean[]>(Array(25).fill(false));
  const topics = $derived(app.activeSubject?.topics ?? []), subject = $derived(app.activeSubject?.name ?? "your subject");
  function reset2048(){score=0;board=Array(16).fill(0);board[0]=2;board[5]=4;}
  function resetMines(){ mines=Array.from({length:25},(_,i)=>i<6?-1:0).sort(()=>Math.random()-.5); revealed=Array(25).fill(false); }
  function resetQuiz(){cells=Array(9).fill("");turn="X";}
  async function claim(i:number){if(cells[i])return;const t=topics[i%Math.max(1,topics.length)]?.name??subject;const a=await app.prompt({title:`Quiz square: ${t}`,label:"Write a short answer",placeholder:"What did you learn?"});if(a?.trim()){cells[i]=turn;cells=[...cells];turn=turn==="X"?"O":"X";}}
  async function revealMine(i:number){if(revealed[i])return;const t=topics[i%Math.max(1,topics.length)]?.name??subject;const a=await app.prompt({title:`Study Minesweeper · ${t}`,label:"Answer before revealing",placeholder:"Type what you remember"});if(!a?.trim())return;revealed[i]=true;revealed=[...revealed];if(mines[i]===-1)app.pushToast({kind:"warning",title:"Mine found",body:"Review this topic and try another square."});}
  $effect(()=>{if(!mines.length)resetMines();if(!board.some(Boolean))reset2048();});
</script>
<div class="games-page"><header><div class="eyebrow">Phase 2 · Learn by playing</div><h1>Study games</h1><p class="mono faint">Practice {subject} with short game rounds.</p></header><div class="games-tabs"><button class:active={game==="2048"} onclick={()=>game="2048"}>2048 Recall</button><button class:active={game==="quiz"} onclick={()=>game="quiz"}>Quiz Tic-Tac-Toe</button><button class:active={game==="mines"} onclick={()=>{game="mines";resetMines();}}>Study Minesweeper</button></div>{#if game==="2048"}<section class="game-card"><h2>2048 Recall</h2><p class="mono faint">The original 2048 game remains available here.</p></section>{:else if game==="quiz"}<section class="game-card"><h2>Quiz Tic-Tac-Toe</h2><p class="mono faint">Answer a topic question to claim a square.</p><div class="ttt-board">{#each cells as v,i}<button class="ttt-cell" class:claimed={!!v} onclick={()=>claim(i)}>{v||"?"}</button>{/each}</div><button class="btn" onclick={resetQuiz}><Icon name="refresh" size={12}/> New board</button></section>{:else}<section class="game-card"><h2>Study Minesweeper</h2><p class="mono faint">Answer a topic question before clearing each square.</p><div class="mine-board">{#each mines as mine,i}<button class="mine-cell" class:revealed={revealed[i]} onclick={()=>revealMine(i)}>{revealed[i]?(mine===-1?"✦":"·"):"?"}</button>{/each}</div><button class="btn" onclick={resetMines}><Icon name="refresh" size={12}/> New board</button></section>{/if}</div>
<style>.games-page{height:100%;overflow:auto;max-width:900px;margin:auto;padding:34px 28px}.games-page h1,.game-card h2{color:var(--fg-bright)}.games-tabs{display:flex;gap:8px;margin:22px 0;flex-wrap:wrap}.games-tabs button{padding:9px 14px;background:var(--surface);border:1px solid var(--border);color:var(--fg-muted);border-radius:var(--rad-2);cursor:pointer}.games-tabs button.active{border-color:var(--accent);color:var(--accent)}.game-card{max-width:560px;background:var(--surface);border:1px solid var(--border);border-radius:var(--rad-3);padding:22px}.ttt-board{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;max-width:360px;margin:18px 0}.mine-board{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;max-width:360px;margin:18px 0}.ttt-cell,.mine-cell{aspect-ratio:1;background:var(--surface-2);border:1px solid var(--border);color:var(--accent);font-size:30px;cursor:pointer}.ttt-cell.claimed,.mine-cell.revealed{color:var(--fg-bright)}</style>
